# Generated by Django 3.0.3 on 2020-02-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
